# Generated by Django 3.2.22 on 2024-07-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Название_пациента')),
                ('Sex', models.CharField(max_length=30, verbose_name=(('Male', 'Мужской'), ('Female', 'Женский')))),
                ('Departments', models.CharField(max_length=30, verbose_name='Отдел')),
                ('Status', models.CharField(max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'db_table': 'patients',
                'managed': True,
            },
        ),
    ]
